### ISSUE TITLE
Some large tests in EventEndPointCallRealIntegrationShould are failing with demo server

### ISSUE THREAD

**Issue by xurxodev** [EyeSeeTea/dhis2-android-sdk#298]
- download_number_of_events_according_to_default_limit
- download_event_with_category_combo_option

Only fail with demo server, android-current server work successfully

**Comment by Amejia481** [comment]
The test that are failing are:
**org.hisp.dhis.android.core.event.EventEndPointCallRealIntegrationShould**
    - download_number_of_events_according_to_default_limit
    - download_event_with_category_combo_option

The source of this problem is that the server **demo** is returning a different set of data than the **android-current** server is returning.

To be specify, the **EventEndPointCall.call()** method is returning in the **demo** server, an Event (**TrZVvga5sO7**) as part of [the event payload](https://play.dhis2.org/demo/api/events.json?orgUnit=DiszpKrYNg8&fields=attributeCategoryOptions,attributeOptionCombo,event,created,lastUpdated,status,coordinate,program,programStage,orgUnit,eventDate,completedDate,dueDate,deleted,dataValues&paging=true&page=1&pageSize=50), and it has some has some data elements (**cF0XbuZkUcC** ,**yV91JsUXuju** ,**z9auvNRRWQJ** and **WY9LjaUQI1q**), that are not been part of the [program payload](https://play.dhis2.org/demo/api/programs.json?fields=id,code,name,displayName,created,lastUpdated,shortName,displayShortName,description,displayDescription,version,captureCoordinates,dataEntryMethod,deleted,displayFrontPageList,displayIncidentDate,enrollmentDateLabel,ignoreOverdueEvents,incidentDateLabel,onlyEnrollOnce,programType,registration,relationshipFromA,relationshipText,selectEnrollmentDatesInFuture,selectIncidentDatesInFuture,useFirstStageDuringRegistration,relatedProgram[id]programStages[id,code,name,displayName,created,lastUpdated,allowGenerateNextVisit,autoGenerateEvent,blockEntryForm,captureCoordinates,deleted,displayGenerateEventBox,executionDateLabel,formType,generatedByEnrollmentDate,hideDueDate,minDaysFromStart,openAfterEnrollment,repeatable,reportDateToUse,sortOrder,standardInterval,validCompleteOnly,programStageDataElements[id,code,created,lastUpdated,allowFutureDate,allowProvidedElsewhere,compulsory,deleted,displayInReports,sortOrder,programStage[id]dataElement[id,code,name,displayName,created,lastUpdated,shortName,displayShortName,description,displayDescription,aggregationType,deleted,dimension,displayFormName,domainType,formName,numberType,valueType,zeroIsSignificant,optionSet[id,version]categoryCombo[id]]]programStageSections[id,code,name,displayName,created,lastUpdated,sortOrder,deleted,dataElements[id]programIndicators[id,program[id]]]]programRules[id,code,name,displayName,created,lastUpdated,deleted,priority,condition,program[id]programStage[id]programRuleActions[id,code,name,displayName,created,lastUpdated,content,data,deleted,location,programRuleActionType,programRule[id]dataElement[id]programIndicator[id]programStage[id]programStageSection[id]trackedEntityAttribute[id]]]programRuleVariables[id,code,name,displayName,created,lastUpdated,deleted,programRuleVariableSourceType,useCodeForOptionSet,program[id]dataElement[id]programStage[id]trackedEntityAttribute[id]]programIndicators[id,code,name,displayName,created,lastUpdated,shortName,displayShortName,description,displayDescription,decimals,deleted,dimensionItem,displayInForm,expression,filter,program[id]]programTrackedEntityAttributes[id,code,name,displayName,created,lastUpdated,shortName,displayShortName,description,displayDescription,allowFutureDate,deleted,displayInList,mandatory,program[id]trackedEntityAttribute[id,code,created,lastUpdated,name,displayName,shortName,displayShortName,description,displayDescription,displayInListNoProgram,displayOnVisitSchedule,expression,generated,inherit,orgunitScope,programScope,pattern,sortOrderInListNoProgram,unique,valueType,searchScope,optionSet[id,version]]]trackedEntity[id]categoryCombo[id]relationshipType[id,code,name,displayName,created,lastUpdated,aIsToB,bIsToA,deleted]&filter=id:in:[eBAyeGv0exc,VBqh0ynB2wv,IpHINAT79UW,ur1Edk5Oe2n,uy2gU8kT1jF,bMcwwoVnbSR,lxAQ7Zs9VYR,WSGAb5XwJ3Y,fDd25txQckK,kla3mAPgvCH,q04UBOqq3rp]&paging=false).

For this reason, every time the **TrackedEntityDataValueStore** tries to insert those data elements on **TrackedEntityDataValue** table gets a **SQLiteConstraintException: FOREIGN KEY**.

**Comment by Amejia481** [comment]
In this particular case when an Event is pointing to data elements are not present in the program payload, the approach will be to ignore them to continue with the synchronization.

**Comment by Amejia481** [comment]
This #300  pull request also solve these tests that are failing in the development branch 

org.hisp.dhis.android.core.LogoutCallRealIntegrationShould
- have_empty_database_when_wipe_db_after_sync_data
- delete_autenticate_user_table_only_when_log_out_after_sync_data
